services:
  poll20:
    container_name: poll20
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOSTNAME: "db"
    volumes:
      - "build-cache:/opt/app/_build"
      - "deps-cache:/opt/app/deps"

  db:
    image: "postgres:17"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "poll20_dev"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres-data:
  build-cache:
  deps-cache: