// Generates src/api-default-fields.ts from the backend's OpenAPI spec (run by `pnpm api:types`).
// Sparse fieldsets (`fields[type]=...`) replace a resource's default fields, so requesting an extra
// field (e.g. an aggregate) means listing the defaults too: `[...defaultFields.game, 'extra']`.
import { readFileSync, writeFileSync } from 'node:fs'

const specPath = '../priv/openapi.json'
const outputPath = 'src/api-default-fields.ts'
// ash_json_api's marker for the fields it serializes when none are requested
const defaultFieldDescription = 'Field included by default.'

interface AttributeSchema {
  description?: string
}

// resource schemas are keyed by their JSON:API type; only they have an attributes object
interface Schema {
  properties?: {
    attributes?: { properties?: Record<string, AttributeSchema> }
  }
}

const spec = JSON.parse(readFileSync(specPath, 'utf8'))
const schemas: Record<string, Schema> = spec.components.schemas

const defaultFieldsByType = Object.fromEntries(
  Object.entries(schemas)
    .flatMap(([type, schema]) => {
      const attributes = schema.properties?.attributes?.properties
      return attributes ? [[type, attributes] as const] : []
    })
    .sort(([type], [otherType]) => type.localeCompare(otherType))
    .map(([type, attributes]) => [
      type,
      Object.entries(attributes)
        .filter(([, attribute]) => attribute.description === defaultFieldDescription)
        .map(([name]) => name),
    ]),
)

writeFileSync(outputPath, `// Generated by scripts/api-default-fields.ts from the OpenAPI spec, don't edit by hand.
export const defaultFields = ${JSON.stringify(defaultFieldsByType, null, 2)} as const
`)
