defmodule Poll20.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:games) do
      add :match_all_owners, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:games) do
      remove :match_all_owners
    end
  end
end