defmodule Poll20.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:session_members) do
      modify :member_id, :uuid, null: true
    end

    alter table(:games) do
      add :players_min, :bigint
      add :players_max, :bigint
    end
  end

  def down do
    alter table(:games) do
      remove :players_max
      remove :players_min
    end

    alter table(:session_members) do
      modify :member_id, :uuid, null: false
    end
  end
end