defmodule Poll20.Repo.Migrations.UniqueVotePerMemberAndGame do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Duplicates from before this index would make it fail: keep each member's latest vote per game
    execute """
    DELETE FROM votes AS older
    USING votes AS newer
    WHERE older.member_id = newer.member_id
      AND older.game_id = newer.game_id
      AND (older.updated_at, older.id) < (newer.updated_at, newer.id)
    """

    create unique_index(:votes, [:member_id, :game_id], name: "votes_unique_member_game_index")
  end

  def down do
    drop_if_exists unique_index(:votes, [:member_id, :game_id],
                     name: "votes_unique_member_game_index"
                   )
  end
end
