defmodule Poll20.Repo.Migrations.DeclareCascadeDeletes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:game_owners, "game_owners_member_id_fkey")

    alter table(:game_owners) do
      modify :member_id,
             references(:members,
               column: :id,
               name: "game_owners_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:game_owners, "game_owners_game_id_fkey")

    alter table(:game_owners) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_owners_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:games, "games_room_id_fkey")

    alter table(:games) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "games_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:members, "members_room_id_fkey")

    alter table(:members) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "members_room_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:session_members, "session_members_member_id_fkey")

    alter table(:session_members) do
      modify :member_id,
             references(:members,
               column: :id,
               name: "session_members_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:session_members, "session_members_session_id_fkey")

    alter table(:session_members) do
      modify :session_id,
             references(:sessions,
               column: :id,
               name: "session_members_session_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:sessions, "sessions_game_id_fkey")

    alter table(:sessions) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "sessions_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:votes, "votes_game_id_fkey")

    alter table(:votes) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "votes_game_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:votes, "votes_member_id_fkey")

    alter table(:votes) do
      modify :member_id,
             references(:members,
               column: :id,
               name: "votes_member_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:votes, "votes_member_id_fkey")

    drop constraint(:votes, "votes_game_id_fkey")

    alter table(:votes) do
      modify :member_id,
             references(:members,
               column: :id,
               name: "votes_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:votes) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "votes_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:sessions, "sessions_game_id_fkey")

    alter table(:sessions) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "sessions_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:session_members, "session_members_session_id_fkey")

    drop constraint(:session_members, "session_members_member_id_fkey")

    alter table(:session_members) do
      modify :session_id,
             references(:sessions,
               column: :id,
               name: "session_members_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:session_members) do
      modify :member_id,
             references(:members,
               column: :id,
               name: "session_members_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:members, "members_room_id_fkey")

    alter table(:members) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "members_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:games, "games_room_id_fkey")

    alter table(:games) do
      modify :room_id,
             references(:rooms,
               column: :id,
               name: "games_room_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:game_owners, "game_owners_game_id_fkey")

    drop constraint(:game_owners, "game_owners_member_id_fkey")

    alter table(:game_owners) do
      modify :game_id,
             references(:games,
               column: :id,
               name: "game_owners_game_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:game_owners) do
      modify :member_id,
             references(:members,
               column: :id,
               name: "game_owners_member_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
