defmodule Poll20.Repo.Migrations.RequireForeignKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Rows missing one of these foreign keys are unusable (unreadable through the
    # policies, or breaking the client), so remove them before adding NOT NULL.
    # Deleting games/sessions cascades to their votes, owners and attendees.
    execute("DELETE FROM games WHERE room_id IS NULL")
    execute("DELETE FROM sessions WHERE game_id IS NULL")
    execute("DELETE FROM session_members WHERE member_id IS NULL")
    execute("DELETE FROM votes WHERE game_id IS NULL OR member_id IS NULL")

    alter table(:games) do
      modify :room_id, :uuid, null: false
    end

    alter table(:session_members) do
      modify :member_id, :uuid, null: false
    end

    alter table(:sessions) do
      modify :game_id, :uuid, null: false
    end

    alter table(:votes) do
      modify :game_id, :uuid, null: false
      modify :member_id, :uuid, null: false
    end
  end

  def down do
    alter table(:votes) do
      modify :member_id, :uuid, null: true
      modify :game_id, :uuid, null: true
    end

    alter table(:sessions) do
      modify :game_id, :uuid, null: true
    end

    alter table(:session_members) do
      modify :member_id, :uuid, null: true
    end

    alter table(:games) do
      modify :room_id, :uuid, null: true
    end
  end
end
