defmodule Poll20.Repo.Migrations.UpgradeToAsh3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:game_owners) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:games) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:members) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:rooms) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :invite_code, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:session_members) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end

    alter table(:sessions) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:votes) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:votes) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :id, :uuid, default: nil
    end

    alter table(:sessions) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :id, :uuid, default: nil
    end

    alter table(:session_members) do
      modify :id, :uuid, default: nil
    end

    alter table(:rooms) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :invite_code, :uuid, default: nil
      modify :id, :uuid, default: nil
    end

    alter table(:members) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :id, :uuid, default: nil
    end

    alter table(:games) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :id, :uuid, default: nil
    end

    alter table(:game_owners) do
      modify :updated_at, :utc_datetime_usec, default: fragment("now()")
      modify :inserted_at, :utc_datetime_usec, default: fragment("now()")
      modify :id, :uuid, default: nil
    end
  end
end
