defmodule Poll20.Repo.Migrations.VoteValueSmallint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:session_members) do
      modify :vote, :smallint
    end

    alter table(:votes) do
      modify :value, :smallint
    end
  end

  def down do
    alter table(:votes) do
      modify :value, :bigint
    end

    alter table(:session_members) do
      modify :vote, :bigint
    end
  end
end
