/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /games operation on game resource */
        get: {
            parameters: {
                query?: {
                    /** @description Filters the query to results with attributes matching the given filter object */
                    filter?: components["schemas"]["game-filter"];
                    /** @description Sort order to apply to the results */
                    sort?: string;
                    /** @description Paginates the response with the limit and offset or keyset pagination. */
                    page?: {
                        after?: string;
                        before?: string;
                        /** @default false */
                        count?: boolean;
                        limit?: number;
                        offset?: number;
                    };
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for game
                         * @example id,name,players_min,players_max,match_all_owners,room_id
                         */
                        game?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            /** @description An array of resource objects representing a game */
                            data?: components["schemas"]["game"][];
                            included?: components["schemas"]["member"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        /** @description /games operation on game resource */
        post: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for game
                         * @example id,name,players_min,players_max,match_all_owners,room_id
                         */
                        game?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request body for the /games operation on game resource */
            requestBody: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                match_all_owners?: boolean | null;
                                name: string;
                                owners?: string[] | null;
                                players_max?: number | null;
                                players_min?: number | null;
                                /** Format: uuid */
                                room_id: string;
                            };
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "game";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["game"];
                            included?: components["schemas"]["member"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /games/:id operation on game resource */
        get: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for game
                         * @example id,name,players_min,players_max,match_all_owners,room_id
                         */
                        game?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["game"];
                            included?: components["schemas"]["member"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        post?: never;
        /** @description /games/:id operation on game resource */
        delete: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for game
                         * @example id,name,players_min,players_max,match_all_owners,room_id
                         */
                        game?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["errors"];
            };
        };
        options?: never;
        head?: never;
        /** @description /games/:id operation on game resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for game
                         * @example id,name,players_min,players_max,match_all_owners,room_id
                         */
                        game?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /games/:id operation on game resource */
            requestBody?: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                match_all_owners?: boolean | null;
                                name?: string | null;
                                owners?: string[] | null;
                                players_max?: number | null;
                                players_min?: number | null;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "game";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["game"];
                            included?: components["schemas"]["member"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
    "/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /members operation on member resource */
        get: {
            parameters: {
                query?: {
                    /** @description Filters the query to results with attributes matching the given filter object */
                    filter?: components["schemas"]["member-filter"];
                    /** @description Sort order to apply to the results */
                    sort?: string;
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for member
                         * @example id,name,room_id
                         */
                        member?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            /** @description An array of resource objects representing a member */
                            data?: components["schemas"]["member"][];
                            included?: components["schemas"]["room"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /members/:id operation on member resource */
        get: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for member
                         * @example id,name,room_id
                         */
                        member?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["member"];
                            included?: components["schemas"]["room"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description /members/:id operation on member resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for member
                         * @example id,name,room_id
                         */
                        member?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /members/:id operation on member resource */
            requestBody?: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                name?: string | null;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "member";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["member"];
                            included?: components["schemas"]["room"][];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /rooms operation on room resource */
        get: {
            parameters: {
                query?: {
                    /** @description Filters the query to results with attributes matching the given filter object */
                    filter?: components["schemas"]["room-filter"];
                    /** @description Sort order to apply to the results */
                    sort?: string;
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for room
                         * @example id,name,invite_code
                         */
                        room?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            /** @description An array of resource objects representing a room */
                            data?: components["schemas"]["room"][];
                            included?: (components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        /** @description /rooms operation on room resource */
        post: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for room
                         * @example id,name,invite_code
                         */
                        room?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request body for the /rooms operation on room resource */
            requestBody: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                name: string;
                            };
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "room";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["room"];
                            included?: (components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /rooms/:id operation on room resource */
        get: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for room
                         * @example id,name,invite_code
                         */
                        room?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["room"];
                            included?: (components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description /rooms/:id operation on room resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for room
                         * @example id,name,invite_code
                         */
                        room?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /rooms/:id operation on room resource */
            requestBody?: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                name?: string | null;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "room";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["room"];
                            included?: (components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
    "/rooms/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description /rooms/:id/join operation on room resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for room
                         * @example id,name,invite_code
                         */
                        room?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /rooms/:id/join operation on room resource */
            requestBody: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                invite_code?: string | null;
                                name: string;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "room";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["room"];
                            included?: (components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
    "/rooms/{id}/kick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description /rooms/:id/kick operation on room resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for room
                         * @example id,name,invite_code
                         */
                        room?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /rooms/:id/kick operation on room resource */
            requestBody: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                invite_code?: string | null;
                                /** Format: uuid */
                                member_id: string;
                                name?: string | null;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "room";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["room"];
                            included?: (components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /sessions operation on session resource */
        get: {
            parameters: {
                query?: {
                    /** @description Filters the query to results with attributes matching the given filter object */
                    filter?: components["schemas"]["session-filter"];
                    /** @description Sort order to apply to the results */
                    sort?: string;
                    /** @description Paginates the response with the limit and offset or keyset pagination. */
                    page?: {
                        after?: string;
                        before?: string;
                        /** @default false */
                        count?: boolean;
                        limit?: number;
                        offset?: number;
                    };
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for session
                         * @example id,comment,inserted_at,updated_at,game_id
                         */
                        session?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            /** @description An array of resource objects representing a session */
                            data?: components["schemas"]["session"][];
                            included?: (components["schemas"]["session_member"] | components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        /** @description /sessions operation on session resource */
        post: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for session
                         * @example id,comment,inserted_at,updated_at,game_id
                         */
                        session?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request body for the /sessions operation on session resource */
            requestBody: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                attendees: Record<string, never>[];
                                comment?: string | null;
                                /** Format: uuid */
                                game_id: string;
                            };
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "session";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["session"];
                            included?: (components["schemas"]["session_member"] | components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /sessions/:id operation on session resource */
        get: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for session
                         * @example id,comment,inserted_at,updated_at,game_id
                         */
                        session?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["session"];
                            included?: (components["schemas"]["session_member"] | components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        post?: never;
        /** @description /sessions/:id operation on session resource */
        delete: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for session
                         * @example id,comment,inserted_at,updated_at,game_id
                         */
                        session?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["errors"];
            };
        };
        options?: never;
        head?: never;
        /** @description /sessions/:id operation on session resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for session
                         * @example id,comment,inserted_at,updated_at,game_id
                         */
                        session?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /sessions/:id operation on session resource */
            requestBody?: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                comment?: string | null;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "session";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["session"];
                            included?: (components["schemas"]["session_member"] | components["schemas"]["member"] | components["schemas"]["game"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
    "/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /votes operation on vote resource */
        get: {
            parameters: {
                query?: {
                    /** @description Filters the query to results with attributes matching the given filter object */
                    filter?: components["schemas"]["vote-filter"];
                    /** @description Sort order to apply to the results */
                    sort?: string;
                    /** @description Paginates the response with the limit and offset or keyset pagination. */
                    page?: {
                        after?: string;
                        before?: string;
                        /** @default false */
                        count?: boolean;
                        limit?: number;
                        offset?: number;
                    };
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for vote
                         * @example id,value,inserted_at,updated_at,game_id,member_id
                         */
                        vote?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            /** @description An array of resource objects representing a vote */
                            data?: components["schemas"]["vote"][];
                            included?: (components["schemas"]["game"] | components["schemas"]["member"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        /** @description /votes operation on vote resource */
        post: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for vote
                         * @example id,value,inserted_at,updated_at,game_id,member_id
                         */
                        vote?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request body for the /votes operation on vote resource */
            requestBody: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                /** Format: uuid */
                                game_id: string;
                                /** Format: uuid */
                                member_id: string;
                                /** @enum {integer} */
                                value: -1 | 1;
                            };
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "vote";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["vote"];
                            included?: (components["schemas"]["game"] | components["schemas"]["member"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/votes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description /votes/:id operation on vote resource */
        get: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for vote
                         * @example id,value,inserted_at,updated_at,game_id,member_id
                         */
                        vote?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["vote"];
                            included?: (components["schemas"]["game"] | components["schemas"]["member"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        put?: never;
        post?: never;
        /** @description /votes/:id operation on vote resource */
        delete: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for vote
                         * @example id,value,inserted_at,updated_at,game_id,member_id
                         */
                        vote?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["errors"];
            };
        };
        options?: never;
        head?: never;
        /** @description /votes/:id operation on vote resource */
        patch: {
            parameters: {
                query?: {
                    /** @description Relationship paths to include in the response */
                    include?: string;
                    /** @description Limits the response fields to only those listed for each type */
                    fields?: {
                        /**
                         * @description Comma separated field names for vote
                         * @example id,value,inserted_at,updated_at,game_id,member_id
                         */
                        vote?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Request body for the /votes/:id operation on vote resource */
            requestBody?: {
                content: {
                    "application/vnd.api+json": {
                        data: {
                            attributes?: {
                                value?: (-1 | 1) | null;
                            };
                            id: string;
                            relationships?: Record<string, never>;
                            /** @enum {unknown} */
                            type?: "vote";
                        };
                    };
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.api+json": {
                            data?: components["schemas"]["vote"];
                            included?: (components["schemas"]["game"] | components["schemas"]["member"])[];
                            meta?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                default: components["responses"]["errors"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Filters the query to results matching the given filter object
         * @example
         */
        "game-filter": {
            and?: components["schemas"]["game-filter"][];
            id?: components["schemas"]["game-filter-id"];
            match_all_owners?: components["schemas"]["game-filter-match_all_owners"];
            name?: components["schemas"]["game-filter-name"];
            not?: components["schemas"]["game-filter"];
            or?: components["schemas"]["game-filter"][];
            owners?: components["schemas"]["member-filter"];
            players_max?: components["schemas"]["game-filter-players_max"];
            players_min?: components["schemas"]["game-filter-players_min"];
            room?: components["schemas"]["room-filter"];
            room_id?: components["schemas"]["game-filter-room_id"];
        };
        /**
         * @description Filters the query to results matching the given filter object
         * @example
         */
        "session-filter": {
            and?: components["schemas"]["session-filter"][];
            attendees?: components["schemas"]["session_member-filter"];
            comment?: components["schemas"]["session-filter-comment"];
            game?: components["schemas"]["game-filter"];
            game_id?: components["schemas"]["session-filter-game_id"];
            id?: components["schemas"]["session-filter-id"];
            inserted_at?: components["schemas"]["session-filter-inserted_at"];
            not?: components["schemas"]["session-filter"];
            or?: components["schemas"]["session-filter"][];
            updated_at?: components["schemas"]["session-filter-updated_at"];
        };
        /** @description A "Resource object" representing a session_member */
        session_member: {
            /** @description An attributes object for a session_member */
            attributes?: {
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                member_id: string;
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                session_id: string;
                /** @description Field included by default. */
                vote?: (-1 | 1 | null) | null;
                /** @description Field included by default. */
                winner: boolean;
            };
            id: string;
            /** @description A relationships object for a session_member */
            relationships?: {
                member?: {
                    /** @description An identifier for member */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
                session?: {
                    /** @description An identifier for session */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
            };
            type: string;
        };
        "session_member-filter-session_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        /** @description A link MUST be represented as either: a string containing the link's URL or a link object. */
        link: string;
        errors: components["schemas"]["error"][];
        "session-filter-inserted_at": {
            eq?: unknown;
            greater_than?: unknown;
            greater_than_or_equal?: unknown;
            in?: unknown[];
            is_distinct_from?: unknown;
            is_nil?: boolean;
            is_not_distinct_from?: unknown;
            less_than?: unknown;
            less_than_or_equal?: unknown;
            not_eq?: unknown;
        };
        "room-filter-invite_code": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "session-filter-id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "session-filter-updated_at": {
            eq?: unknown;
            greater_than?: unknown;
            greater_than_or_equal?: unknown;
            in?: unknown[];
            is_distinct_from?: unknown;
            is_nil?: boolean;
            is_not_distinct_from?: unknown;
            less_than?: unknown;
            less_than_or_equal?: unknown;
            not_eq?: unknown;
        };
        links: {
            [key: string]: components["schemas"]["link"];
        };
        error: {
            /** @description An application-specific error code, expressed as a string value. */
            code?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description A unique identifier for this particular occurrence of the problem. */
            id?: string;
            links?: components["schemas"]["links"];
            source?: {
                /** @description A string indicating which query parameter caused the error. */
                parameter?: string;
                /** @description A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute]. */
                pointer?: string;
            };
            /** @description The HTTP status code applicable to this problem, expressed as a string value. */
            status?: string;
            /** @description A short, human-readable summary of the problem. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization. */
            title?: string;
        };
        /** @description A "Resource object" representing a vote */
        vote: {
            /** @description An attributes object for a vote */
            attributes?: {
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                game_id: string;
                /** @description Field included by default. */
                inserted_at: unknown;
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                member_id: string;
                /** @description Field included by default. */
                updated_at: unknown;
                /**
                 * @description Field included by default.
                 * @enum {integer}
                 */
                value: -1 | 1;
            };
            id: string;
            /** @description A relationships object for a vote */
            relationships?: {
                game?: {
                    /** @description An identifier for game */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
                member?: {
                    /** @description An identifier for member */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
            };
            type: string;
        };
        /**
         * @description Filters the query to results matching the given filter object
         * @example
         */
        "member-filter": {
            and?: components["schemas"]["member-filter"][];
            id?: components["schemas"]["member-filter-id"];
            name?: components["schemas"]["member-filter-name"];
            not?: components["schemas"]["member-filter"];
            or?: components["schemas"]["member-filter"][];
            room?: components["schemas"]["room-filter"];
            room_id?: components["schemas"]["member-filter-room_id"];
        };
        "session-filter-game_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "vote-filter-updated_at": {
            eq?: unknown;
            greater_than?: unknown;
            greater_than_or_equal?: unknown;
            in?: unknown[];
            is_distinct_from?: unknown;
            is_nil?: boolean;
            is_not_distinct_from?: unknown;
            less_than?: unknown;
            less_than_or_equal?: unknown;
            not_eq?: unknown;
        };
        "game-filter-match_all_owners": {
            eq?: boolean;
            greater_than?: boolean;
            greater_than_or_equal?: boolean;
            in?: boolean[];
            is_distinct_from?: boolean;
            is_nil?: boolean;
            is_not_distinct_from?: boolean;
            less_than?: boolean;
            less_than_or_equal?: boolean;
            not_eq?: boolean;
        };
        /** @description A "Resource object" representing a member */
        member: {
            /** @description An attributes object for a member */
            attributes?: {
                /** @description Field included by default. */
                name: string;
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                room_id: string;
            };
            id: string;
            /** @description A relationships object for a member */
            relationships?: {
                room?: {
                    /** @description An identifier for room */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
            };
            type: string;
        };
        "vote-filter-member_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "session-filter-comment": {
            contains?: string;
            eq?: string;
            greater_than?: string;
            greater_than_or_equal?: string;
            ilike?: string;
            in?: string[];
            is_distinct_from?: string;
            is_nil?: boolean;
            is_not_distinct_from?: string;
            less_than?: string;
            less_than_or_equal?: string;
            like?: string;
            not_eq?: string;
            string_ends_with?: string;
            string_starts_with?: string;
        };
        "vote-filter-value": {
            /** @enum {integer} */
            eq?: -1 | 1;
            /** @enum {integer} */
            greater_than?: -1 | 1;
            /** @enum {integer} */
            greater_than_or_equal?: -1 | 1;
            in?: (-1 | 1)[];
            /** @enum {integer} */
            is_distinct_from?: -1 | 1;
            is_nil?: boolean;
            /** @enum {integer} */
            is_not_distinct_from?: -1 | 1;
            /** @enum {integer} */
            less_than?: -1 | 1;
            /** @enum {integer} */
            less_than_or_equal?: -1 | 1;
            /** @enum {integer} */
            not_eq?: -1 | 1;
        };
        /** @description A "Resource object" representing a session */
        session: {
            /** @description An attributes object for a session */
            attributes?: {
                /** @description Field included by default. */
                comment?: (string | null) | null;
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                game_id: string;
                /** @description Field included by default. */
                inserted_at: unknown;
                /** @description Field included by default. */
                updated_at: unknown;
            };
            id: string;
            /** @description A relationships object for a session */
            relationships?: {
                attendees?: {
                    /** @description Relationship data for attendees */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    }[];
                };
                game?: {
                    /** @description An identifier for game */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
            };
            type: string;
        };
        "session_member-filter-id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        /**
         * @description Filters the query to results matching the given filter object
         * @example
         */
        "session_member-filter": {
            and?: components["schemas"]["session_member-filter"][];
            id?: components["schemas"]["session_member-filter-id"];
            member?: components["schemas"]["member-filter"];
            member_id?: components["schemas"]["session_member-filter-member_id"];
            not?: components["schemas"]["session_member-filter"];
            or?: components["schemas"]["session_member-filter"][];
            session?: components["schemas"]["session-filter"];
            session_id?: components["schemas"]["session_member-filter-session_id"];
            vote?: components["schemas"]["session_member-filter-vote"];
            winner?: components["schemas"]["session_member-filter-winner"];
        };
        "member-filter-room_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "session_member-filter-vote": {
            /** @enum {integer} */
            eq?: -1 | 1;
            /** @enum {integer} */
            greater_than?: -1 | 1;
            /** @enum {integer} */
            greater_than_or_equal?: -1 | 1;
            in?: (-1 | 1)[];
            /** @enum {integer} */
            is_distinct_from?: -1 | 1;
            is_nil?: boolean;
            /** @enum {integer} */
            is_not_distinct_from?: -1 | 1;
            /** @enum {integer} */
            less_than?: -1 | 1;
            /** @enum {integer} */
            less_than_or_equal?: -1 | 1;
            /** @enum {integer} */
            not_eq?: -1 | 1;
        };
        /**
         * @description Filters the query to results matching the given filter object
         * @example
         */
        "vote-filter": {
            and?: components["schemas"]["vote-filter"][];
            game?: components["schemas"]["game-filter"];
            game_id?: components["schemas"]["vote-filter-game_id"];
            id?: components["schemas"]["vote-filter-id"];
            inserted_at?: components["schemas"]["vote-filter-inserted_at"];
            member?: components["schemas"]["member-filter"];
            member_id?: components["schemas"]["vote-filter-member_id"];
            not?: components["schemas"]["vote-filter"];
            or?: components["schemas"]["vote-filter"][];
            updated_at?: components["schemas"]["vote-filter-updated_at"];
            value?: components["schemas"]["vote-filter-value"];
        };
        "game-filter-id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "game-filter-room_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "member-filter-name": {
            contains?: string;
            eq?: string;
            greater_than?: string;
            greater_than_or_equal?: string;
            ilike?: string;
            in?: string[];
            is_distinct_from?: string;
            is_nil?: boolean;
            is_not_distinct_from?: string;
            less_than?: string;
            less_than_or_equal?: string;
            like?: string;
            not_eq?: string;
            string_ends_with?: string;
            string_starts_with?: string;
        };
        "session_member-filter-member_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "game-filter-name": {
            contains?: string;
            eq?: string;
            greater_than?: string;
            greater_than_or_equal?: string;
            ilike?: string;
            in?: string[];
            is_distinct_from?: string;
            is_nil?: boolean;
            is_not_distinct_from?: string;
            less_than?: string;
            less_than_or_equal?: string;
            like?: string;
            not_eq?: string;
            string_ends_with?: string;
            string_starts_with?: string;
        };
        "vote-filter-inserted_at": {
            eq?: unknown;
            greater_than?: unknown;
            greater_than_or_equal?: unknown;
            in?: unknown[];
            is_distinct_from?: unknown;
            is_nil?: boolean;
            is_not_distinct_from?: unknown;
            less_than?: unknown;
            less_than_or_equal?: unknown;
            not_eq?: unknown;
        };
        "room-filter-id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "vote-filter-game_id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        /** @description A "Resource object" representing a game */
        game: {
            /** @description An attributes object for a game */
            attributes?: {
                /** @description Field included by default. */
                match_all_owners: boolean;
                /** @description Field included by default. */
                name: string;
                /** @description Field included by default. */
                players_max?: (number | null) | null;
                /** @description Field included by default. */
                players_min?: (number | null) | null;
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                room_id: string;
            };
            id: string;
            /** @description A relationships object for a game */
            relationships?: {
                owners?: {
                    /** @description Relationship data for owners */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    }[];
                };
                room?: {
                    /** @description An identifier for room */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    } | null;
                };
            };
            type: string;
        };
        /**
         * @description Filters the query to results matching the given filter object
         * @example
         */
        "room-filter": {
            and?: components["schemas"]["room-filter"][];
            games?: components["schemas"]["game-filter"];
            id?: components["schemas"]["room-filter-id"];
            invite_code?: components["schemas"]["room-filter-invite_code"];
            members?: components["schemas"]["member-filter"];
            name?: components["schemas"]["room-filter-name"];
            not?: components["schemas"]["room-filter"];
            or?: components["schemas"]["room-filter"][];
        };
        "member-filter-id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
        "room-filter-name": {
            contains?: string;
            eq?: string;
            greater_than?: string;
            greater_than_or_equal?: string;
            ilike?: string;
            in?: string[];
            is_distinct_from?: string;
            is_nil?: boolean;
            is_not_distinct_from?: string;
            less_than?: string;
            less_than_or_equal?: string;
            like?: string;
            not_eq?: string;
            string_ends_with?: string;
            string_starts_with?: string;
        };
        "game-filter-players_max": {
            eq?: number;
            greater_than?: number;
            greater_than_or_equal?: number;
            in?: number[];
            is_distinct_from?: number;
            is_nil?: boolean;
            is_not_distinct_from?: number;
            less_than?: number;
            less_than_or_equal?: number;
            not_eq?: number;
        };
        /** @description A "Resource object" representing a room */
        room: {
            /** @description An attributes object for a room */
            attributes?: {
                /**
                 * Format: uuid
                 * @description Field included by default.
                 */
                invite_code: string;
                /** @description Field included by default. */
                name: string;
            };
            id: string;
            /** @description A relationships object for a room */
            relationships?: {
                games?: {
                    /** @description Relationship data for games */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    }[];
                };
                members?: {
                    /** @description Relationship data for members */
                    data?: {
                        id: string;
                        meta?: {
                            [key: string]: unknown;
                        };
                        type: string;
                    }[];
                };
            };
            type: string;
        };
        "session_member-filter-winner": {
            eq?: boolean;
            greater_than?: boolean;
            greater_than_or_equal?: boolean;
            in?: boolean[];
            is_distinct_from?: boolean;
            is_nil?: boolean;
            is_not_distinct_from?: boolean;
            less_than?: boolean;
            less_than_or_equal?: boolean;
            not_eq?: boolean;
        };
        "game-filter-players_min": {
            eq?: number;
            greater_than?: number;
            greater_than_or_equal?: number;
            in?: number[];
            is_distinct_from?: number;
            is_nil?: boolean;
            is_not_distinct_from?: number;
            less_than?: number;
            less_than_or_equal?: number;
            not_eq?: number;
        };
        "vote-filter-id": {
            /** Format: uuid */
            eq?: string;
            /** Format: uuid */
            greater_than?: string;
            /** Format: uuid */
            greater_than_or_equal?: string;
            in?: string[];
            /** Format: uuid */
            is_distinct_from?: string;
            is_nil?: boolean;
            /** Format: uuid */
            is_not_distinct_from?: string;
            /** Format: uuid */
            less_than?: string;
            /** Format: uuid */
            less_than_or_equal?: string;
            /** Format: uuid */
            not_eq?: string;
        };
    };
    responses: {
        /** @description General Error */
        errors: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/vnd.api+json": components["schemas"]["errors"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
