// Generated by scripts/api-default-fields.ts from the OpenAPI spec, don't edit by hand.
export const defaultFields = {
  "game": [
    "match_all_owners",
    "name",
    "players_max",
    "players_min",
    "room_id"
  ],
  "member": [
    "name",
    "room_id"
  ],
  "room": [
    "invite_code",
    "name"
  ],
  "session": [
    "comment",
    "game_id",
    "inserted_at",
    "updated_at"
  ],
  "session_member": [
    "member_id",
    "session_id",
    "vote",
    "winner"
  ],
  "vote": [
    "game_id",
    "inserted_at",
    "member_id",
    "updated_at",
    "value"
  ]
} as const
