// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonCopy: typeof import('~icons/carbon/copy')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonProgressBarRound: typeof import('~icons/carbon/progress-bar-round')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    IFaArrowDown: typeof import('~icons/fa/arrow-down')['default']
    IFaArrowUp: typeof import('~icons/fa/arrow-up')['default']
    IFaCog: typeof import('~icons/fa/cog')['default']
    IFaController: typeof import('~icons/fa/controller')['default']
    IFaGamepad: typeof import('~icons/fa/gamepad')['default']
    IFaRefresh: typeof import('~icons/fa/refresh')['default']
    IFaSolidArrowLeft: typeof import('~icons/fa-solid/arrow-left')['default']
    IFaSolidPencilAlt: typeof import('~icons/fa-solid/pencil-alt')['default']
    IFaSolidTimes: typeof import('~icons/fa-solid/times')['default']
    IFaUser: typeof import('~icons/fa/user')['default']
    IMaterialSymbolsCheckBox: typeof import('~icons/material-symbols/check-box')['default']
    IMaterialSymbolsCheckBoxOutlineBlank: typeof import('~icons/material-symbols/check-box-outline-blank')['default']
    IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    IMdiClock: typeof import('~icons/mdi/clock')['default']
    IMdiComment: typeof import('~icons/mdi/comment')['default']
    IMdiTrophy: typeof import('~icons/mdi/trophy')['default']
    IMdiUsers: typeof import('~icons/mdi/users')['default']
    PForm: typeof import('./components/PForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheRoomNav: typeof import('./components/TheRoomNav.vue')['default']
  }
}
