// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./components/TheFooter copy.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    ICarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonCopy: typeof import('~icons/carbon/copy')['default']
    ICarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    ICarbonEdit: typeof import('~icons/carbon/edit')['default']
    ICarbonProgressBarRound: typeof import('~icons/carbon/progress-bar-round')['default']
    ICarbonTimes: typeof import('~icons/carbon/times')['default']
    ICarbonWarning: typeof import('~icons/carbon/warning')['default']
    IFaArrowDown: typeof import('~icons/fa/arrow-down')['default']
    IFaArrowUp: typeof import('~icons/fa/arrow-up')['default']
    IFaCheck: typeof import('~icons/fa/check')['default']
    IFaCog: typeof import('~icons/fa/cog')['default']
    IFaGroup: typeof import('~icons/fa/group')['default']
    IFaRefresh: typeof import('~icons/fa/refresh')['default']
    IFaSolidArrowLeft: typeof import('~icons/fa-solid/arrow-left')['default']
    IFaSolidPencil: typeof import('~icons/fa-solid/pencil')['default']
    IFaSolidPencilAlt: typeof import('~icons/fa-solid/pencil-alt')['default']
    IFaSolidTimes: typeof import('~icons/fa-solid/times')['default']
    IFaTimes: typeof import('~icons/fa/times')['default']
    IIcBaselineClose: typeof import('~icons/ic/baseline-close')['default']
    IIcRoundQuestionMark: typeof import('~icons/ic/round-question-mark')['default']
    IMaterialSymbolsCheckBox: typeof import('~icons/material-symbols/check-box')['default']
    IMaterialSymbolsCheckBoxEmpty: typeof import('~icons/material-symbols/check-box-empty')['default']
    IMaterialSymbolsCheckBoxOutline: typeof import('~icons/material-symbols/check-box-outline')['default']
    IMaterialSymbolsCheckBoxOutlineBlank: typeof import('~icons/material-symbols/check-box-outline-blank')['default']
    IMaterialSymbolsCheckBoxOutlineEmpty: typeof import('~icons/material-symbols/check-box-outline-empty')['default']
    IMaterialSymbolsCloseRounded: typeof import('~icons/material-symbols/close-rounded')['default']
    IMaterialSymbolsEdit: typeof import('~icons/material-symbols/edit')['default']
    IMdiClock: typeof import('~icons/mdi/clock')['default']
    IMdiComment: typeof import('~icons/mdi/comment')['default']
    IMdiTrophy: typeof import('~icons/mdi/trophy')['default']
    IMdiUser: typeof import('~icons/mdi/user')['default']
    IMdiUsers: typeof import('~icons/mdi/users')['default']
    ITypcnTimes: typeof import('~icons/typcn/times')['default']
    PForm: typeof import('./components/PForm.vue')['default']
    README: typeof import('./components/README.md')['default']
    RoomNav: typeof import('./components/RoomNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheRoomNav: typeof import('./components/TheRoomNav.vue')['default']
  }
}
