/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/join/[invite_code]': RouteRecordInfo<
      '/join/[invite_code]',
      '/join/:invite_code',
      { invite_code: ParamValue<true> },
      { invite_code: ParamValue<false> },
      | never
    >,
    '/room': RouteRecordInfo<
      '/room',
      '/room',
      Record<never, never>,
      Record<never, never>,
      | '/room/[id]/games'
      | '/room/[id]/history'
      | '/room/[id]/poll'
      | '/room/[id]/settings'
      | '/room/[id]/statistics'
    >,
    '/room/[id]/games': RouteRecordInfo<
      '/room/[id]/games',
      '/room/:id/games',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/room/[id]/history': RouteRecordInfo<
      '/room/[id]/history',
      '/room/:id/history',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/room/[id]/poll': RouteRecordInfo<
      '/room/[id]/poll',
      '/room/:id/poll',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/room/[id]/settings': RouteRecordInfo<
      '/room/[id]/settings',
      '/room/:id/settings',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/room/[id]/statistics': RouteRecordInfo<
      '/room/[id]/statistics',
      '/room/:id/statistics',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/join/[invite_code].vue': {
      routes:
        | '/join/[invite_code]'
      views:
        | never
      pathParamNames:
        | 'invite_code'
    }
    'src/pages/room.vue': {
      routes:
        | '/room'
        | '/room/[id]/games'
        | '/room/[id]/history'
        | '/room/[id]/poll'
        | '/room/[id]/settings'
        | '/room/[id]/statistics'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/room/[id]/games.vue': {
      routes:
        | '/room/[id]/games'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/room/[id]/history.vue': {
      routes:
        | '/room/[id]/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/room/[id]/poll.vue': {
      routes:
        | '/room/[id]/poll'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/room/[id]/settings.vue': {
      routes:
        | '/room/[id]/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/room/[id]/statistics.vue': {
      routes:
        | '/room/[id]/statistics'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
